name: Build and Deploy Astro to Repo B

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev=8.15.1-1.1build4 || sudo apt-get install -y libvips-dev

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            ./node_modules
          key: bun-deps-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            bun-deps-

      - name: Install dependencies
        run: bun install

      - name: Rebuild sharp
        run: bunx --bun npm rebuild sharp

      - name: Verify Sharp version
        run: bun pm ls sharp

      - name: Build Astro
        run: bun run build

      - name: Deploy dist to Repository B
        env:
          REPO_B: https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/zxc7563598/astro-theme-pure-dist.git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "junjie.he.925@gmail.com"

          git clone --depth 1 $REPO_B temp-repo
          cd temp-repo

          rm -rf dist/*
          mkdir -p dist

          cp -R ../dist/* dist/
          cp ../package.json ../bun.lock ./

          git add .
          git commit -m "Update dist, package.json and bun.lock from main branch of A" || echo "No changes to commit"
          git push origin main
